version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default

linters:
  default: standard
  enable:
    - revive
    - gocritic
    - goconst
    - nakedret
    - tagalign
