// Code generated by go generate; DO NOT EDIT.

package main

//export dprint_plugin_version_4
func dprint_plugin_version_4() uint32 {
	return runtime.DprintPluginVersion4()
}

//export register_config
func register_config(configID uint32) {
	runtime.RegisterConfig(configID)
}

//export release_config
func release_config(configID uint32) {
	runtime.ReleaseConfig(configID)
}

//export get_config_diagnostics
func get_config_diagnostics(configID uint32) uint32 {
	return runtime.GetConfigDiagnostics(configID)
}

//export get_resolved_config
func get_resolved_config(configID uint32) uint32 {
	return runtime.GetResolvedConfig(configID)
}

//export get_config_file_matching
func get_config_file_matching(configID uint32) uint32 {
	return runtime.GetConfigFileMatching(configID)
}

//export get_license_text
func get_license_text() uint32 {
	return runtime.GetLicenseText()
}

//export get_plugin_info
func get_plugin_info() uint32 {
	return runtime.GetPluginInfo()
}

//export set_file_path
func set_file_path() {
	runtime.SetFilePath()
}

//export set_override_config
func set_override_config() {
	runtime.SetOverrideConfig()
}

//export format
func format(configID uint32) uint32 {
	return runtime.Format(configID)
}

//export format_range
func format_range(configID uint32, rangeStart uint32, rangeEnd uint32) uint32 {
	return runtime.FormatRange(configID, rangeStart, rangeEnd)
}

//export get_formatted_text
func get_formatted_text() uint32 {
	return runtime.GetFormattedText()
}

//export get_error_text
func get_error_text() uint32 {
	return runtime.GetErrorText()
}

//export check_config_updates
func check_config_updates() uint32 {
	return runtime.CheckConfigUpdates()
}

//export get_shared_bytes_ptr
func get_shared_bytes_ptr() uint32 {
	return runtime.GetSharedBytesPtr()
}

//export clear_shared_bytes
func clear_shared_bytes(size uint32) uint32 {
	return runtime.ClearSharedBytes(size)
}

func main() {}
