// Package main generates wasm entrypoint boilerplate for this plugin project.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

type templateData struct {
	Runtime string
}

const sourceTemplate = `// Code generated by go generate; DO NOT EDIT.

package main

//export dprint_plugin_version_4
func dprint_plugin_version_4() uint32 {
	return {{ .Runtime }}.DprintPluginVersion4()
}

//export register_config
func register_config(configID uint32) {
	{{ .Runtime }}.RegisterConfig(configID)
}

//export release_config
func release_config(configID uint32) {
	{{ .Runtime }}.ReleaseConfig(configID)
}

//export get_config_diagnostics
func get_config_diagnostics(configID uint32) uint32 {
	return {{ .Runtime }}.GetConfigDiagnostics(configID)
}

//export get_resolved_config
func get_resolved_config(configID uint32) uint32 {
	return {{ .Runtime }}.GetResolvedConfig(configID)
}

//export get_config_file_matching
func get_config_file_matching(configID uint32) uint32 {
	return {{ .Runtime }}.GetConfigFileMatching(configID)
}

//export get_license_text
func get_license_text() uint32 {
	return {{ .Runtime }}.GetLicenseText()
}

//export get_plugin_info
func get_plugin_info() uint32 {
	return {{ .Runtime }}.GetPluginInfo()
}

//export set_file_path
func set_file_path() {
	{{ .Runtime }}.SetFilePath()
}

//export set_override_config
func set_override_config() {
	{{ .Runtime }}.SetOverrideConfig()
}

//export format
func format(configID uint32) uint32 {
	return {{ .Runtime }}.Format(configID)
}

//export format_range
func format_range(configID uint32, rangeStart uint32, rangeEnd uint32) uint32 {
	return {{ .Runtime }}.FormatRange(configID, rangeStart, rangeEnd)
}

//export get_formatted_text
func get_formatted_text() uint32 {
	return {{ .Runtime }}.GetFormattedText()
}

//export get_error_text
func get_error_text() uint32 {
	return {{ .Runtime }}.GetErrorText()
}

//export check_config_updates
func check_config_updates() uint32 {
	return {{ .Runtime }}.CheckConfigUpdates()
}

//export get_shared_bytes_ptr
func get_shared_bytes_ptr() uint32 {
	return {{ .Runtime }}.GetSharedBytesPtr()
}

//export clear_shared_bytes
func clear_shared_bytes(size uint32) uint32 {
	return {{ .Runtime }}.ClearSharedBytes(size)
}

func main() {}
`

func main() {
	var (
		runtimeVar = flag.String("runtime", "runtime", "runtime variable name")
		outFile    = flag.String("out", "main_generated.go", "output file path")
	)
	flag.Parse()

	if *runtimeVar == "" {
		exitWithError(fmt.Errorf("runtime variable name must not be empty"))
	}
	if *outFile == "" {
		exitWithError(fmt.Errorf("output file path must not be empty"))
	}

	tmpl, err := template.New("main-generated").Parse(sourceTemplate)
	if err != nil {
		exitWithError(err)
	}

	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, templateData{Runtime: *runtimeVar}); err != nil {
		exitWithError(err)
	}

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		exitWithError(err)
	}

	if err := os.WriteFile(*outFile, formatted, 0o644); err != nil {
		exitWithError(err)
	}
}

func exitWithError(err error) {
	_, _ = fmt.Fprintf(os.Stderr, "gen-main-boilerplate: %v\n", err)
	os.Exit(1)
}
